Repository hmcts/ccd-case-print-service, pull requests merged in 2020-04, with the labels that each got.

#218 Rdm 7440
  README.md
  aat/build.gradle
  aat/src/resources/features/F-000/S-000.td.json
Labels: ns:ccd, rel:ccd-case-print-service-pr-218

#219 Cleaning up ASE terraform
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, rel:ccd-case-print-service-pr-219

#212 RDM-7843-Stale-PR
  .github/stale.yml
Labels: ns:ccd, rel:ccd-case-print-service-pr-212

#215 RDM-7867-Update-base-chart
  charts/ccd-case-print-service/Chart.yaml
  charts/ccd-case-print-service/requirements.yaml
Labels: ns:ccd, rel:ccd-case-print-service-pr-215

#210 RDM-7633 - Migrate Print Service to OIDC
  config/default.yaml
  src/main/service/case-service.ts
  src/main/user/user-request-authorizer.spec.ts
  src/main/user/user-resolver.ts
  src/main/views/case-data.njk
Labels: ns:ccd, rel:ccd-case-print-service-pr-210
