Repository hmcts/ccd-case-print-service, pull requests merged in 2020-03, with the labels that each got.

#211 update assign-deep and enable aks aat
  Jenkinsfile_CNP
  yarn.lock
Labels: ns:ccd, rel:ccd-case-print-service-pr-211

#216 Update ingress host for public access
  charts/ccd-case-print-service/Chart.yaml
  charts/ccd-case-print-service/values.yaml
Labels: ns:ccd, rel:ccd-case-print-service-pr-216

#213 Add properties volume for secrets to be resolved
  package.json
  src/main/server.ts
  yarn.lock
Labels: ns:ccd, rel:ccd-case-print-service-pr-213

#217 RDM-7899-Slack
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-print-service-pr-217
