Repository hmcts/ccd-case-print-service, pull requests merged in 2020-07, with the labels that each got.

#230 Test 8936
  .gitignore
  Jenkinsfile_CNP
  aat/build.gradle
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-230

#229 introduce security audit to pipeline and fix CVEs
  .gitignore
  Jenkinsfile_CNP
  aat/build.gradle
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-229

#231 RDM-8995 : Develop-develop Preview
  Jenkinsfile_CNP
  bin/run-yarn-audit.sh
  ccd-yarn-audit-known-issues
  charts/ccd-case-print-service/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-231

#228 Fix smoke tests
  Jenkinsfile_CNP
  aat/build.gradle
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-228
