Repository hmcts/ccd-case-print-service, pull requests merged in 2021-07, with the labels that each got.

#298 Temporarily suppress CVE issues
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-298

#297 Resolve CVEs detected by yarn audit in Case Print Service component
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-297

#304 CCD-1572: Integrate Fortify Scan into Nightly Pipelines
  .gitignore
  Jenkinsfile_nightly
  aat/build.gradle
  aat/config/fortify-client.properties
  aat/gradle/wrapper/gradle-wrapper.properties
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-304
