Repository hmcts/ccd-case-print-service, pull requests merged in 2022-08, with the labels that each got.

#397 CCD-3560: Updated glob-parent to 6.0.1 and removed suppression
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-397

#405 CCD-3467: Updated CVE-2022-25758 suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-405

#411 CCD-3639: Fix preview deployment issues
  Jenkinsfile_CNP
  charts/ccd-case-print-service/values.preview.template.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-411

#410 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-410

#408 CCD-3467: CVE-2022-25758 - removed dependency node-sass (unused dependency)
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-408

#409 CCD-3633 fix for CVE-2022-33987
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-409
