Repository hmcts/ccd-case-print-service, pull requests merged in 2022-09, with the labels that each got.

#413 CCD-3634 fix for CVE-2022-25858
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-413

#412 CCD-3569 Fix docker build failures in Node JS repos after multi arch …
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-412

#399 CCD-3539 : Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-399
