Repository hmcts/ccd-case-print-service, pull requests merged in 2022-07, with the labels that each got.

#392 CVE-2022-31129 : Added Suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-392

#372 CCD-2496 Update all repos with multi arch base images
  Dockerfile
  Jenkinsfile_CNP
  acb.tpl.yaml
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-372

#393 CCD-3466: Updated moment to 2.29.4 and removed suppression
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-393

#395 CCD-3467: ccd-case-print-service CVE-2022-25758 suppression updated
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-395

#388 CCD-965: Remove Temporary Sonar Exclusions ccd-case-print-service
  sonar-project.properties
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-388

#396 CCD-3560: CVE-2021-35065 suppress
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-396

#400 CCD-3467: ccd-case-print-service CVE-2022-25758 suppress update
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-400

#398 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-case-print-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-398
