Repository hmcts/ccd-case-print-service, pull requests merged in 2022-12, with the labels that each got.

#428 CCD-4022 Dependabot Prototype pollution in webpack loader-utils - res…
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-428

#436 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped nodejs…
  charts/ccd-case-print-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-436

#438 CCD-4108: Suppressions for: CVE-2022-38900, CVE-2022-22984
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-438

#432 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-432

#441 CCD-4134 CVE-2022-46175 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-441
