Repository hmcts/ccd-case-print-service, pull requests merged in 2022-10, with the labels that each got.

#419 CCD-3785: Suppress CVE-2022-40764
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-419

#417 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-417, keep-helm

#420 CCD-3743: Removed redundant package resolutions
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-420

#421 CCD-3785: CVE-2022-40764 Fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-421
