Repository hmcts/ccd-case-print-service, pull requests merged in 2022-03, with the labels that each got.

#368 CVE-2022-0235
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-368

#369 CCD-2708
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-369

#370 cve suppression and updated fortify client version to 1.2.2
  aat/build.gradle
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-370
