Repository hmcts/ccd-case-print-service, pull requests merged in 2022-04, with the labels that each got.

#373 Origin/ccd 2792 fix remaining dependant bot issue
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-373

#377 CCD-2965
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-377

#375 Revert "Revert "Origin/ccd 2792 fix remaining dependant bot issue""
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-375

#379 --Fix the nightly build
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-379

#381 yarn-audit-know-issues updated due to dependency failure
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-381

#380 CCD-2976: CVE-2022-24785 dependency fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-380
