Repository hmcts/ccd-case-print-service, pull requests merged in 2022-02, with the labels that each got.

#353 CCD-2543: Ignore Fortify scan results
  aat/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-353

#354 CVE-2020-24025 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-354

#360 CCD-2655: Suppress CVE pending investigation
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-360

#364 CVE-2021-23555
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-364

#365 update helm version
  charts/ccd-case-print-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-365

#362 CVE-2020-24025
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-362

#350 CVE-2020-28503
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-350
