Repository hmcts/ccd-case-print-service, pull requests merged in 2023-06, with the labels that each got.

#477 Updating renovate config
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-477

#478 CCD-4712 : fix for sonar gate failure
  src/main/util/fetch.ts
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-478

#481 CCD-4766 : Fix suppressions syntax
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-481

#482 CCD-4712 : test sonar fix
  src/main/util/fetch.ts
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-482
