Repository hmcts/ccd-case-print-service, pull requests merged in 2023-01, with the labels that each got.

#443 CCD-4134 CVE-2022-46175 Redo Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-443

#444 CCD-4134 CVE-2022-46175 Redo Suppression 2nd Time
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-444

#442 CCD-4134 CVE-2022-46175 json5 v2.2.2 resolution added, yarn install r…
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-442

#448 CCD-4156: Added suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-448

#437 CCD-4097: Auto-suppress CVEs - Node JS apps
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-437

#450 CCD-4173: Auto-suppress CVEs do not allow empty commit
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-450

#440 CCD-3796 Update Node Version - node version upgraded to 16.15.0
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  acb.tpl.yaml
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-440
