Repository hmcts/ccd-case-print-service, pull requests merged in 2024-11, with the labels that each got.

#512 CCD-5861 : Fix CVE-2024-45296
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-512

#513 CME-37: java 21
  aat/build.gradle
  aat/gradle/wrapper/gradle-wrapper.jar
  aat/gradle/wrapper/gradle-wrapper.properties
  aat/gradlew.bat
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-513, enable_keep_helm

#519 suppressions added to fix master pipeline
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-519
