Repository hmcts/ccd-case-print-service, pull requests merged in 2024-09, with the labels that each got.

#502 CCD-966 - Take that, Probate Man
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-502

#505 CCD-5861 : CVE-2024-45296 : Suppressions added
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-505

#507 CCD-5861 : CVE-2024-45296 : updated suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-507

#508 case_print_cve
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-508

#511 CVE_reDO
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-511
