Repository hmcts/ccd-case-print-service, pull requests merged in 2025-01, with the labels that each got.

#520 CCD-5931:
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-520

#525 CME-311: Update azurerm
  aat/build.gradle
  infrastructure/state.tf
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/no-changes, rel:ccd-case-print-service-pr-525

#531 CME-311: downgrade ccd-test-definitions to 7.24.2 (latest tagged)
  aat/build.gradle
Labels: ns:ccd, prd:ccd

#526 CCD-5561 & CCD-5195:
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-526
