Repository hmcts/ccd-case-print-service, pull requests merged in 2025-03, with the labels that each got.

#533 CCD-6111:
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-533

#538 remove package-manager
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-538

#535 CCD-6193 update base chart version
  charts/ccd-case-print-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-print-service-pr-535
